=== jeffclj67/Data_Project/db/table.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="root">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="STUDENT" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="ID" type="xs:int"/>
            <xs:element name="LNAME" type="xs:string"/>
            <xs:element name="FNAME" type="xs:string"/>
            <xs:element name="SCHOOL_NO" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="SCHOOL" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="SCHOOL_NO" type="xs:int"/>
            <xs:element name="SCHOOL_NAME" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="TUTOR" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="TUTOR_ID" type="xs:int"/>
            <xs:element name="NAME" type="xs:string"/>
            <xs:element name="RATE" type="xs:int"/>
            <xs:element name="COMPANY" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="QUESTION_RAISED" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="QUESTION_ID" type="xs:int"/>
            <xs:element name="STU_ID" type="xs:int"/>
            <xs:element name="SUBJECT" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="WORKS_ON" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="TUTOR_ID" type="xs:int"/>
            <xs:element name="QUESTION_ID" type="xs:int"/>
            <xs:element name="HOURS" type="xs:int"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== jeffclj67/Data_Project/data_management/xml/table.xml
<?xml version="1.0" encoding="UTF-8"?>
<root
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="/table.xsd">
  <STUDENT>
    <ID>101</ID>
    <FNAME>Ana</FNAME>
    <LNAME>Lincole</LNAME>
    <SCHOOL_NO>3</SCHOOL_NO>
  </STUDENT>
  <STUDENT>
    <ID>102</ID>
    <FNAME>Antonio</FNAME>
    <LNAME>Wang</LNAME>
    <SCHOOL_NO>2</SCHOOL_NO>
  </STUDENT>
  <STUDENT>
    <ID>103</ID>
    <FNAME>Thomas</FNAME>
    <LNAME>Devon</LNAME>
    <SCHOOL_NO>5</SCHOOL_NO>
  </STUDENT>
  <STUDENT>
    <ID>104</ID>
    <FNAME>Christina</FNAME>
    <LNAME>Cruz</LNAME>
    <SCHOOL_NO>1</SCHOOL_NO>
  </STUDENT>
  <STUDENT>
    <ID>105</ID>
    <FNAME>Hanna</FNAME>
    <LNAME>Rodriguez</LNAME>
    <SCHOOL_NO>6</SCHOOL_NO>
  </STUDENT>
  <STUDENT>
    <ID>106</ID>
    <FNAME>Yang</FNAME>
    <LNAME>Pontes</LNAME>
    <SCHOOL_NO>3</SCHOOL_NO>
  </STUDENT>

  <SCHOOL>
    <SCHOOL_NO>1</SCHOOL_NO>
    <SCHOOL_NAME>UOIT</SCHOOL_NAME>
  </SCHOOL>
  <SCHOOL>
    <SCHOOL_NO>2</SCHOOL_NO>
    <SCHOOL_NAME>UofT</SCHOOL_NAME>
  </SCHOOL>
  <SCHOOL>
    <SCHOOL_NO>3</SCHOOL_NO>
    <SCHOOL_NAME>UBC</SCHOOL_NAME>
  </SCHOOL>
  <SCHOOL>
    <SCHOOL_NO>4</SCHOOL_NO>
    <SCHOOL_NAME>Mac</SCHOOL_NAME>
  </SCHOOL>
  <SCHOOL>
    <SCHOOL_NO>5</SCHOOL_NO>
    <SCHOOL_NAME>Queen</SCHOOL_NAME>
  </SCHOOL>
  <SCHOOL>
    <SCHOOL_NO>6</SCHOOL_NO>
    <SCHOOL_NAME>Western</SCHOOL_NAME>
  </SCHOOL>

  <TUTOR>
    <TUTOR_ID>201</TUTOR_ID>
    <NAME>Janete Limeira</NAME>
    <RATE>15</RATE>
    <COMPANY>Aplus</COMPANY>
  </TUTOR>
  <TUTOR>
    <TUTOR_ID>202</TUTOR_ID>
    <NAME>Hari Kumar</NAME>
    <RATE>12</RATE>
    <COMPANY>Aplus</COMPANY>
  </TUTOR>
  <TUTOR>
    <TUTOR_ID>203</TUTOR_ID>
    <NAME>Palle Ibsen</NAME>
    <RATE>16</RATE>
    <COMPANY>Excellent</COMPANY>
  </TUTOR>
  <TUTOR>
    <TUTOR_ID>204</TUTOR_ID>
    <NAME>Paul Henriot</NAME>
    <RATE>15</RATE>
    <COMPANY>Easypass</COMPANY>
  </TUTOR>
  <TUTOR>
    <TUTOR_ID>205</TUTOR_ID>
    <NAME>Liu Wong</NAME>
    <RATE>13</RATE>
    <COMPANY>Easypass</COMPANY>
  </TUTOR>
  <TUTOR>
    <TUTOR_ID>206</TUTOR_ID>
    <NAME>Matti Karittunen</NAME>
    <RATE>14</RATE>
    <COMPANY>Easypass</COMPANY>
  </TUTOR>

  <QUESTION_RAISED>
    <QUESTION_ID>1</QUESTION_ID>
    <STU_ID>101</STU_ID>
    <SUBJECT>Calculus</SUBJECT>
  </QUESTION_RAISED>
  <QUESTION_RAISED>
    <QUESTION_ID>2</QUESTION_ID>
    <STU_ID>102</STU_ID>
    <SUBJECT>Physics</SUBJECT>
  </QUESTION_RAISED>
  <QUESTION_RAISED>
    <QUESTION_ID>3</QUESTION_ID>
    <STU_ID>102</STU_ID>
    <SUBJECT>English</SUBJECT>
  </QUESTION_RAISED>
  <QUESTION_RAISED>
    <QUESTION_ID>4</QUESTION_ID>
    <STU_ID>104</STU_ID>
    <SUBJECT>Chemistry</SUBJECT>
  </QUESTION_RAISED>
  <QUESTION_RAISED>
    <QUESTION_ID>5</QUESTION_ID>
    <STU_ID>105</STU_ID>
    <SUBJECT>Calculus</SUBJECT>
  </QUESTION_RAISED>
  <QUESTION_RAISED>
    <QUESTION_ID>6</QUESTION_ID>
    <STU_ID>103</STU_ID>
    <SUBJECT>Physics</SUBJECT>
  </QUESTION_RAISED>

  <WORKS_ON>
    <TUTOR_ID>201</TUTOR_ID>
    <QUESTION_ID>3</QUESTION_ID>
    <HOURS>3</HOURS>
  </WORKS_ON>
  <WORKS_ON>
    <TUTOR_ID>202</TUTOR_ID>
    <QUESTION_ID>1</QUESTION_ID>
    <HOURS>4</HOURS>
  </WORKS_ON>
  <WORKS_ON>
    <TUTOR_ID>202</TUTOR_ID>
    <QUESTION_ID>2</QUESTION_ID>
    <HOURS>2</HOURS>
  </WORKS_ON>
  <WORKS_ON>
    <TUTOR_ID>205</TUTOR_ID>
    <QUESTION_ID>4</QUESTION_ID>
    <HOURS>3</HOURS>
  </WORKS_ON>
  <WORKS_ON>
    <TUTOR_ID>205</TUTOR_ID>
    <QUESTION_ID>5</QUESTION_ID>
    <HOURS>2</HOURS>
  </WORKS_ON>
  <WORKS_ON>
    <TUTOR_ID>206</TUTOR_ID>
    <QUESTION_ID>6</QUESTION_ID>
    <HOURS>2</HOURS>
  </WORKS_ON>
</root>
